#!/usr/bin/env bash
# bench/microbench.sh — reproduce the docs/BENCHMARK.md appendix
# microbenchmarks and record RAW measurements, one JSONL line each, to
# bench/micro/<group>.jsonl:
#
#   {"bench","variant","backend","model","n_cases","pack_size","samples",
#    "wall_ms","calls","exit","timestamp","git_rev"}
#
# `calls` is counted from the per-run $HUNGJURY_HOME/calls.jsonl audit
# log. Each measurement gets a fresh home under bench/micro/home-*/
# (gitignored via `bench/*/home*/`) which also keeps stdout.log,
# stderr.log, and the batch --out file as evidence.
#
# Usage: bench/microbench.sh <group>          (build first: cargo build)
#   latency       1 `decide` per backend, run in parallel     ~3 calls
#   juror-models  codex terra/luna/sol @low, 20-case batch    ~60 calls
#   throughput    single decide + batch@10/20/50 per backend  ~243 calls
#   pack          decide x SEQ_N sequential, batch, batch --pack PACK_N
#                                                             ~59 calls
#   all           every group above                           ~365 calls
#
# Every group burns real juror CLI quota — see bench/README.md.
# Conditions mirror the appendix: single juror per run, --min-quorum 1
# (except pack's jury rows), --escalate off --no-cache --no-memory, and
# max_concurrency=6 (the binary default; bench.toml uses 8).
#
# Env overrides (defaults reproduce the appendix):
#   BIN=./target/debug/hungjury   DAILY_CAP=5000   MAX_CONCURRENCY=6
#   LATENCY_BACKENDS="devin:swe-2-medium claude:haiku codex:gpt-5.6-sol@low"
#   LATENCY_CASES=bench/support/cases.jsonl
#   JUROR_MODELS="terra luna sol"   JUROR_N=20
#   JUROR_CASES=bench/support/cases.jsonl
#   THROUGHPUT_BACKENDS="devin:swe-2-medium codex:gpt-5.6-terra@low claude:haiku"
#   THROUGHPUT_SIZES="10 20 50"  THROUGHPUT_CASES=bench/adversarial/cases.jsonl
#   PACK_JUROR=devin:swe-2-medium   PACK_SAMPLES=3   PACK_N=12   SEQ_N=10
#   PACK_CASES=bench/adversarial/cases.jsonl
set -euo pipefail
cd "$(dirname "$0")/.."

BIN="${BIN:-./target/debug/hungjury}"
MICRO_DIR="${MICRO_DIR:-bench/micro}"
DAILY_CAP="${DAILY_CAP:-5000}"
MAX_CONCURRENCY="${MAX_CONCURRENCY:-6}"

LATENCY_BACKENDS="${LATENCY_BACKENDS:-devin:swe-2-medium claude:haiku codex:gpt-5.6-sol@low}"
LATENCY_CASES="${LATENCY_CASES:-bench/support/cases.jsonl}"

JUROR_MODELS="${JUROR_MODELS:-terra luna sol}"
JUROR_N="${JUROR_N:-20}"
JUROR_CASES="${JUROR_CASES:-bench/support/cases.jsonl}"

THROUGHPUT_BACKENDS="${THROUGHPUT_BACKENDS:-devin:swe-2-medium codex:gpt-5.6-terra@low claude:haiku}"
THROUGHPUT_SIZES="${THROUGHPUT_SIZES:-10 20 50}"
THROUGHPUT_CASES="${THROUGHPUT_CASES:-bench/adversarial/cases.jsonl}"

PACK_JUROR="${PACK_JUROR:-devin:swe-2-medium}"
PACK_SAMPLES="${PACK_SAMPLES:-3}"
PACK_N="${PACK_N:-12}"
SEQ_N="${SEQ_N:-10}"
PACK_CASES="${PACK_CASES:-bench/adversarial/cases.jsonl}"

usage() {
  cat >&2 <<'EOF'
usage: bench/microbench.sh <latency|juror-models|throughput|pack|all>
Reproduces docs/BENCHMARK.md appendix microbenchmarks; appends one JSONL
measurement line per run to bench/micro/<group>.jsonl. Burns real juror
CLI quota (~365 calls for `all`) — see bench/README.md and the header
comment for env overrides.
EOF
}

GROUP="${1:-}"
case "$GROUP" in
  latency | juror-models | throughput | pack | all) ;;
  *) usage; exit 1 ;;
esac

[ -x "$BIN" ] || { echo "hungjury binary not found at $BIN — build first: cargo build" >&2; exit 1; }
for f in "$LATENCY_CASES" "$JUROR_CASES" "$THROUGHPUT_CASES" "$PACK_CASES"; do
  [ -f "$f" ] || { echo "missing cases file: $f" >&2; exit 1; }
done

mkdir -p "$MICRO_DIR"
GIT_REV=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
SCRATCH=$(mktemp -d "$MICRO_DIR/home-scratch-XXXXXX")
CFG="$SCRATCH/microbench.toml"
cat > "$CFG" <<EOF
# generated by bench/microbench.sh — everything else = binary defaults
[limits]
daily_cap = $DAILY_CAP
max_concurrency = $MAX_CONCURRENCY
EOF

now_ms() {
  if [ -n "${EPOCHREALTIME:-}" ]; then
    local t="${EPOCHREALTIME%???}"
    printf '%s' "${t/./}"
  else
    date +%s%3N
  fi
}

new_home() { mktemp -d "$MICRO_DIR/home-$1-XXXXXX"; }

calls_in() {
  local f="$1/calls.jsonl"
  if [ -f "$f" ]; then wc -l < "$f" | tr -d ' '; else echo 0; fi
}

# measure <home> <hungjury argv...> → echoes "wall_ms calls exit".
# hungjury exit 2 (hung keys) is a valid outcome, not an error.
measure() {
  local home="$1"; shift
  local t0 t1 rc
  t0=$(now_ms)
  HUNGJURY_HOME="$home" "$BIN" --config "$CFG" "$@" \
    >"$home/stdout.log" 2>"$home/stderr.log" && rc=0 || rc=$?
  t1=$(now_ms)
  printf '%s %s %s\n' "$((t1 - t0))" "$(calls_in "$home")" "$rc"
}

# emit <group> <variant> <juror-spec> <n_cases> <pack_size> <samples> <wall_ms> <calls> <exit>
emit() {
  local group="$1" variant="$2" spec="$3"
  printf '{"bench":"%s","variant":"%s","backend":"%s","model":"%s","n_cases":%d,"pack_size":%d,"samples":%d,"wall_ms":%d,"calls":%d,"exit":%d,"timestamp":"%s","git_rev":"%s"}\n' \
    "$group" "$variant" "${spec%%:*}" "${spec#*:}" "$4" "$5" "$6" "$7" "$8" "$9" \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$GIT_REV" >> "$MICRO_DIR/$group.jsonl"
  printf '  %-26s %-30s n=%-3s wall=%sms calls=%s exit=%s\n' \
    "$group/$variant" "$spec" "$4" "$7" "$8" "$9"
}

# slice <src> <n> <dst> → writes first n lines, echoes actual count.
slice() {
  head -n "$2" "$1" > "$3"
  local n; n=$(wc -l < "$3" | tr -d ' ')
  [ "$n" -gt 0 ] || { echo "slice of $1 is empty" >&2; exit 1; }
  [ "$n" -lt "$2" ] && echo "warn: $1 has only $n lines (< $2)" >&2
  printf '%s\n' "$n"
}

# --- groups ---------------------------------------------------------------

bench_latency() {
  echo "== latency: single-call floor, one decide per backend (parallel) =="
  slice "$LATENCY_CASES" 1 "$SCRATCH/latency-req.json" >/dev/null
  local spec
  for spec in $LATENCY_BACKENDS; do
    (
      home=$(new_home latency)
      read -r w c e < <(measure "$home" decide "$SCRATCH/latency-req.json" \
        --jurors "$spec" --min-quorum 1 --escalate off --no-cache --no-memory)
      emit latency decide "$spec" 1 0 1 "$w" "$c" "$e"
    ) &
  done
  wait
}

bench_juror_models() {
  echo "== juror-models: codex tiers @low, $JUROR_N-case batch, 1 juror =="
  local n spec home m
  n=$(slice "$JUROR_CASES" "$JUROR_N" "$SCRATCH/juror-cases.jsonl")
  for m in $JUROR_MODELS; do
    spec="codex:gpt-5.6-$m@low"
    home=$(new_home "juror-$m")
    read -r w c e < <(measure "$home" batch "$SCRATCH/juror-cases.jsonl" \
      --out "$home/out.jsonl" \
      --jurors "$spec" --min-quorum 1 --escalate off --no-cache --no-memory)
    emit juror-models "batch@$n" "$spec" "$n" 0 1 "$w" "$c" "$e"
  done
}

bench_throughput() {
  echo "== throughput: decide + batch@{$THROUGHPUT_SIZES// /,} per backend =="
  local spec home n actual
  slice "$THROUGHPUT_CASES" 1 "$SCRATCH/tp-req.json" >/dev/null
  for spec in $THROUGHPUT_BACKENDS; do
    home=$(new_home tp-1)
    read -r w c e < <(measure "$home" decide "$SCRATCH/tp-req.json" \
      --jurors "$spec" --min-quorum 1 --escalate off --no-cache --no-memory)
    emit throughput decide "$spec" 1 0 1 "$w" "$c" "$e"
    for n in $THROUGHPUT_SIZES; do
      actual=$(slice "$THROUGHPUT_CASES" "$n" "$SCRATCH/tp-$n.jsonl")
      home=$(new_home "tp-b$n")
      read -r w c e < <(measure "$home" batch "$SCRATCH/tp-$n.jsonl" \
        --out "$home/out.jsonl" \
        --jurors "$spec" --min-quorum 1 --escalate off --no-cache --no-memory)
      emit throughput "batch@$actual" "$spec" "$actual" 0 1 "$w" "$c" "$e"
    done
  done
}

bench_pack() {
  echo "== pack: decide x $SEQ_N sequential vs batch vs batch --pack $PACK_N =="
  local home t0 t1 fails i n
  # Row 1 of the appendix table: sequential decides vs one batch.
  n=$(slice "$PACK_CASES" "$SEQ_N" "$SCRATCH/seq.jsonl")
  home=$(new_home pack-seq)
  t0=$(now_ms); fails=0
  for i in $(seq 1 "$n"); do
    sed -n "${i}p" "$SCRATCH/seq.jsonl" > "$home/req.json"
    HUNGJURY_HOME="$home" "$BIN" --config "$CFG" decide "$home/req.json" \
      --jurors "$PACK_JUROR" --samples 1 --min-quorum 1 \
      --escalate off --no-cache --no-memory \
      >>"$home/stdout.log" 2>>"$home/stderr.log" || fails=$((fails + 1))
  done
  t1=$(now_ms)
  emit pack decide-seq "$PACK_JUROR" "$n" 0 1 "$((t1 - t0))" "$(calls_in "$home")" "$fails"

  home=$(new_home pack-batch1)
  read -r w c e < <(measure "$home" batch "$SCRATCH/seq.jsonl" \
    --out "$home/out.jsonl" \
    --jurors "$PACK_JUROR" --samples 1 --min-quorum 1 \
    --escalate off --no-cache --no-memory)
  emit pack batch "$PACK_JUROR" "$n" 0 1 "$w" "$c" "$e"

  # Row 2: concurrent vs packed with a samples=N jury (3 ballots/item).
  n=$(slice "$PACK_CASES" "$PACK_N" "$SCRATCH/pack.jsonl")
  home=$(new_home pack-batch)
  read -r w c e < <(measure "$home" batch "$SCRATCH/pack.jsonl" \
    --out "$home/out.jsonl" \
    --jurors "$PACK_JUROR" --samples "$PACK_SAMPLES" \
    --escalate off --no-cache --no-memory)
  emit pack batch "$PACK_JUROR" "$n" 0 "$PACK_SAMPLES" "$w" "$c" "$e"

  home=$(new_home pack-packed)
  read -r w c e < <(measure "$home" batch "$SCRATCH/pack.jsonl" \
    --out "$home/out.jsonl" --pack "$n" \
    --jurors "$PACK_JUROR" --samples "$PACK_SAMPLES" \
    --escalate off --no-cache --no-memory)
  emit pack pack "$PACK_JUROR" "$n" "$n" "$PACK_SAMPLES" "$w" "$c" "$e"
}

# --- run ------------------------------------------------------------------

echo "microbench: group=$GROUP bin=$BIN out=$MICRO_DIR cap=$DAILY_CAP conc=$MAX_CONCURRENCY rev=$GIT_REV"
case "$GROUP" in
  latency) bench_latency ;;
  juror-models) bench_juror_models ;;
  throughput) bench_throughput ;;
  pack) bench_pack ;;
  all) bench_latency; bench_juror_models; bench_throughput; bench_pack ;;
esac
echo "done — measurements appended to $MICRO_DIR/<group>.jsonl"
